FROM alpine
RUN apk add --no-cache openssh-client

RUN mkdir -p -m 0700 ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_hosts
RUN --mount=type=ssh \
  ssh -T git@github.com 2>&1 | tee /hello

ONBUILD RUN mkdir -p -m 0700 ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_hosts
ONBUILD RUN --mount=type=ssh \
  ssh -T git@github.com 2>&1 | tee /hello
